[package]
name = "lanparty"
version = "0.1.0"
edition = "2024"
description = "LAN communication and peer discovery."
license = "MIT"
repository = "https://github.com/s4njusabu/lanparty"
readme = "README.md"

[dependencies]
ipnet = "2.12.1"
petname = "3.1.0"
ratatui = "0.30.2"
serde = { version = "1.0.229", features = ["derive"] }
bincode = { version = "2.0.0", features = ["serde"] }
